[package]
name = "esp32-c3-sensor-node"
version = "0.1.0"
authors = ["nplongx <nplong.dev@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[lib]
name = "esp32_c3_sensor_node"
path = "src/lib.rs"
crate-type = ["staticlib"]
harness = false

[profile.release]
opt-level = "s"
lto = true
codegen-units = 1
strip = "symbols"
panic = "abort"

[profile.dev]
debug = true
opt-level = "z"

[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }


[dependencies]
log = "0.4"
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hmac = "0.12"
sha2 = "0.10"
hex = "0.4"
lazy_static = "1.5"

esp-idf-svc = "0.52.1"
esp-idf-hal = "0.46.2"
esp-idf-sys = "0.37.2"
ds18b20 = "0.1.1"
one-wire-bus = "0.1.1"

[build-dependencies]
embuild = { version = "0.33", features = ["espidf"] }
