[build]
target = "riscv32imc-esp-espidf"

[target.'cfg(target_os = "espidf")']
linker = "ldproxy"
runner = "espflash flash --monitor"
rustflags = ["--cfg", "espidf_time64"]

[unstable]
build-std = ["std", "panic_abort"]

[env]
MCU = "esp32c3"
ESP_IDF_VERSION = "v5.5.3"
ESP_IDF_TOOLS_INSTALL_DIR = "workspace"

HYDRAGROW_WIFI_SSID = { value = "", force = false }
HYDRAGROW_WIFI_PASSWORD = { value = "", force = false }
HYDRAGROW_MQTT_URL = { value = "mqtt://localhost:1883", force = false }
HYDRAGROW_MQTT_COMMAND_SECRET = { value = "", force = false }
HYDRAGROW_DEVICE_ID = { value = "device_001", force = false }
HYDRAGROW_MQTT_USER = { value = "", force = false }
HYDRAGROW_MQTT_PASSWORD = { value = "", force = false }
