# Dependencies are arranged such that the longest running and the others run in
# parallel, but no time is wasted on tasks that are unlikely to succeed.

steps:
  # Synchronzied with Cargo.toml's rust-version
  test:1.76:
    depends_on: [test:stable]
    image: docker.io/rust:1.76
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - cargo version
    - cargo test

  test:stable:
    depends_on: []
    image: docker.io/rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - cargo version
    - cargo test

  test:nightly:
    depends_on: []
    image: docker.io/rustlang/rust:nightly
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - rustup component add miri
    - cargo version
    - cargo test
    - cargo miri test

  readme:
    depends_on: [fmt]
    image: docker.io/rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - cargo install cargo-doc2readme
    - cargo doc2readme --check

  fmt:
    depends_on: [lint]
    image: docker.io/rust:latest
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - rustup component add rustfmt
    - cargo fmt --check

  lint:
    depends_on: []
    image: docker.io/rustlang/rust:nightly
    environment:
      CARGO_TERM_COLOR: always
    commands:
    - rustup component add clippy
    - RUSTFLAGS="-D warnings" cargo check 
    - cargo clippy -- --deny clippy::all
    - RUSTDOCFLAGS="-D warnings" cargo doc
    failure: ignore

when:
  - branch: main
    event: push
  - event: pull_request
