[package]
name = "esp32-c3-mist-weaver-os"
version = "0.2.0"
authors = ["nplongx <nplong.dev@gmail.com>"]
edition = "2021"
resolver = "2"
rust-version = "1.82"

[[bin]]
name = "esp32-c3-mist-weaver-os"
harness = false                  # do not use the built-in cargo test harness -> resolve rust-analyzer errors

[profile.release]
opt-level = "s"   # Tối ưu hóa cho dung lượng (hoặc dùng "z" để ép nhỏ nhất có thể)
lto = true        # Bật Link-Time Optimization (Build sẽ lâu hơn nhưng file nhỏ hơn)
codegen-units = 1 # Giúp LTO hoạt động tốt nhất
strip = "symbols" # Xóa bỏ các symbol debug không cần thiết trên file release
panic = "abort"   # Xóa code xử lý stack-unwinding khi panic

[profile.dev]
debug = true    # Symbols are nice, and they don't increase the size on Flash
opt-level = "z"
[patch.crates-io]
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys.git" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal.git" }
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc.git" }

[dependencies]
log = "0.4"
tracing = { version = "0.1", features = ["log"] }
tracing-subscriber = { version = "0.3", default-features = false, features = ["registry"] }
serde = "1.0.228"
anyhow = "1.0.102"
serde_json = "1.0.149"

esp-idf-svc = "0.52.1"
esp-idf-hal = "0.46.2"
ds18b20 = "0.1.1"
one-wire-bus = "0.1.1"

esp-idf-sys = "0.37.2"

hydragrow-shared = { path = "../hydragrow-shared" }
hydragrow-controller-core = { path = "../hydragrow-controller-core" }
uuid = { version = "1.20.0", features = ["v4"] }
lazy_static = "1.5.0"
pcf857x = "0.5.0"
embedded-hal = "1.0.0"

hmac = "0.12"
sha2 = "0.10"
hex = "0.4"

libc = ">=0.2.155"

[build-dependencies]
embuild = "0.33"
