ALTER TABLE dosing_calibration
    ADD COLUMN IF NOT EXISTS ec_gain_dynamic REAL NOT NULL DEFAULT 0.01,
    ADD COLUMN IF NOT EXISTS ph_up_dynamic REAL NOT NULL DEFAULT 0.01,
    ADD COLUMN IF NOT EXISTS ph_down_dynamic REAL NOT NULL DEFAULT 0.01,
    ADD COLUMN IF NOT EXISTS dynamic_sample_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS dynamic_confidence REAL NOT NULL DEFAULT 0.0,
    ADD COLUMN IF NOT EXISTS last_dynamic_update TIMESTAMPTZ,
    ADD COLUMN IF NOT EXISTS dynamic_model_version VARCHAR(32) NOT NULL DEFAULT 'v1';
