ALTER TABLE IF EXISTS dosing_calibration
    ADD COLUMN IF NOT EXISTS best_ec_ratio REAL NOT NULL DEFAULT 0.4,
    ADD COLUMN IF NOT EXISTS best_ph_ratio REAL NOT NULL DEFAULT 0.2,
    ADD COLUMN IF NOT EXISTS tuner_state INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS kalman_confidence JSONB;
